// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_asset.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :execrows
INSERT INTO asset
(id, name, warranty_expiry, status, end_of_life)
VALUES (?, ?, ?, ?, ?)
`

type CreateAssetParams struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	WarrantyExpiry sql.NullTime   `json:"warranty_expiry"`
	Status         sql.NullString `json:"status"`
	EndOfLife      sql.NullTime   `json:"end_of_life"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAsset,
		arg.ID,
		arg.Name,
		arg.WarrantyExpiry,
		arg.Status,
		arg.EndOfLife,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAssetFile = `-- name: CreateAssetFile :execrows
INSERT INTO asset_file
(content_hash, mime_type, original_filename, category, asset_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateAssetFileParams struct {
	ContentHash      string `json:"content_hash"`
	MimeType         string `json:"mime_type"`
	OriginalFilename string `json:"original_filename"`
	Category         string `json:"category"`
	AssetID          string `json:"asset_id"`
}

func (q *Queries) CreateAssetFile(ctx context.Context, arg CreateAssetFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAssetFile,
		arg.ContentHash,
		arg.MimeType,
		arg.OriginalFilename,
		arg.Category,
		arg.AssetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
