// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_task.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCompletionLog = `-- name: CreateCompletionLog :execrows
INSERT INTO completion_logs
(id, completed_at, task_id)
VALUES (?, ?, ?)
`

type CreateCompletionLogParams struct {
	ID          uuid.UUID    `json:"id"`
	CompletedAt sql.NullTime `json:"completed_at"`
	TaskID      string       `json:"task_id"`
}

func (q *Queries) CreateCompletionLog(ctx context.Context, arg CreateCompletionLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCompletionLog, arg.ID, arg.CompletedAt, arg.TaskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTask = `-- name: CreateTask :execrows
INSERT INTO tasks
(id, name, last_completed, next_date, start_date, end_date, asset_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID            uuid.UUID    `json:"id"`
	Name          string       `json:"name"`
	LastCompleted sql.NullTime `json:"last_completed"`
	NextDate      sql.NullTime `json:"next_date"`
	StartDate     sql.NullTime `json:"start_date"`
	EndDate       sql.NullTime `json:"end_date"`
	AssetID       string       `json:"asset_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.Name,
		arg.LastCompleted,
		arg.NextDate,
		arg.StartDate,
		arg.EndDate,
		arg.AssetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createTaskRecurrence = `-- name: CreateTaskRecurrence :execrows
INSERT INTO task_recurrences
(id, amount, duration_type, task_id)
VALUES (?, ?, ?, ?)
`

type CreateTaskRecurrenceParams struct {
	ID           uuid.UUID `json:"id"`
	Amount       int64     `json:"amount"`
	DurationType string    `json:"duration_type"`
	TaskID       string    `json:"task_id"`
}

func (q *Queries) CreateTaskRecurrence(ctx context.Context, arg CreateTaskRecurrenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTaskRecurrence,
		arg.ID,
		arg.Amount,
		arg.DurationType,
		arg.TaskID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
