// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_asset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteAsset = `-- name: DeleteAsset :execrows
DELETE FROM assets
WHERE id = ?
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAssetFile = `-- name: DeleteAssetFile :execrows
DELETE FROM asset_files
WHERE asset_id = ? AND content_hash = ?
`

func (q *Queries) DeleteAssetFile(ctx context.Context, assetID string, contentHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAssetFile, assetID, contentHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
