// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_asset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteAssetByID = `-- name: DeleteAssetByID :execrows
DELETE FROM assets
WHERE id = ?
`

func (q *Queries) DeleteAssetByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAssetByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAssetFileByAssetID = `-- name: DeleteAssetFileByAssetID :execrows
DELETE FROM asset_files
WHERE asset_id = ?
`

func (q *Queries) DeleteAssetFileByAssetID(ctx context.Context, assetID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAssetFileByAssetID, assetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFileByContentHash = `-- name: DeleteFileByContentHash :execrows
DELETE FROM files
WHERE content_hash = ?
`

func (q *Queries) DeleteFileByContentHash(ctx context.Context, contentHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFileByContentHash, contentHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
