// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_task.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteCompletionLogByID = `-- name: DeleteCompletionLogByID :execrows
DELETE FROM completion_logs
WHERE id = ?
`

func (q *Queries) DeleteCompletionLogByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCompletionLogByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTaskByID = `-- name: DeleteTaskByID :execrows
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTaskByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTaskRecurrenceByID = `-- name: DeleteTaskRecurrenceByID :execrows
DELETE FROM task_recurrences
WHERE id = ?
`

func (q *Queries) DeleteTaskRecurrenceByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTaskRecurrenceByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
