// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Asset struct {
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	WarrantyExpiry  sql.NullTime `json:"warranty_expiry"`
	Availability    string       `json:"availability"`
	AttentionNeeded string       `json:"attention_needed"`
	EndOfLife       sql.NullTime `json:"end_of_life"`
}

type AssetFile struct {
	AssetID          uuid.UUID `json:"asset_id"`
	ContentHash      string    `json:"content_hash"`
	OriginalFilename string    `json:"original_filename"`
}

type CompletionLog struct {
	ID          uuid.UUID    `json:"id"`
	CompletedAt sql.NullTime `json:"completed_at"`
	TaskID      uuid.UUID    `json:"task_id"`
}

type File struct {
	ContentHash string `json:"content_hash"`
	MimeType    string `json:"mime_type"`
	Path        string `json:"path"`
}

type Task struct {
	ID            uuid.UUID    `json:"id"`
	Name          string       `json:"name"`
	LastCompleted sql.NullTime `json:"last_completed"`
	NextDate      sql.NullTime `json:"next_date"`
	StartDate     sql.NullTime `json:"start_date"`
	EndDate       sql.NullTime `json:"end_date"`
	AssetID       uuid.UUID    `json:"asset_id"`
}

type TaskRecurrence struct {
	ID           uuid.UUID `json:"id"`
	Amount       int64     `json:"amount"`
	DurationType string    `json:"duration_type"`
	TaskID       uuid.UUID `json:"task_id"`
}
