// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Asset struct {
	ID             uuid.UUID    `json:"id"`
	Name           string       `json:"name"`
	WarrantyExpiry sql.NullTime `json:"warranty_expiry"`
	Status         string       `json:"status"`
	EndOfLife      sql.NullTime `json:"end_of_life"`
}

type AssetFile struct {
	ContentHash      string `json:"content_hash"`
	MimeType         string `json:"mime_type"`
	OriginalFilename string `json:"original_filename"`
	Category         string `json:"category"`
	AssetID          string `json:"asset_id"`
}

type CompletionLog struct {
	ID          uuid.UUID    `json:"id"`
	CompletedAt sql.NullTime `json:"completed_at"`
	TaskID      string       `json:"task_id"`
}

type Task struct {
	ID            uuid.UUID    `json:"id"`
	Name          string       `json:"name"`
	LastCompleted sql.NullTime `json:"last_completed"`
	NextDate      sql.NullTime `json:"next_date"`
	StartDate     sql.NullTime `json:"start_date"`
	EndDate       sql.NullTime `json:"end_date"`
	AssetID       string       `json:"asset_id"`
}

type TaskRecurrence struct {
	ID           uuid.UUID `json:"id"`
	Amount       int64     `json:"amount"`
	DurationType string    `json:"duration_type"`
	TaskID       string    `json:"task_id"`
}
