// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Asset struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	WarrantyExpiry sql.NullTime   `json:"warranty_expiry"`
	Status         sql.NullString `json:"status"`
	EndOfLife      sql.NullTime   `json:"end_of_life"`
}

type AssetFile struct {
	ContentHash      string `json:"content_hash"`
	MimeType         string `json:"mime_type"`
	OriginalFilename string `json:"original_filename"`
	Category         string `json:"category"`
	AssetID          string `json:"asset_id"`
}
