// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_asset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listAllAssets = `-- name: ListAllAssets :many
SELECT asset.id, asset.name, asset.warranty_expiry, asset.status, asset.end_of_life, asset_file.content_hash, asset_file.mime_type, asset_file.original_filename, asset_file.category, asset_file.asset_id
FROM asset
INNER JOIN asset_file
  ON asset.id = asset_file.asset_id
ORDER BY asset.id
`

type ListAllAssetsRow struct {
	Asset     Asset     `json:"asset"`
	AssetFile AssetFile `json:"asset_file"`
}

func (q *Queries) ListAllAssets(ctx context.Context) ([]*ListAllAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllAssetsRow
	for rows.Next() {
		var i ListAllAssetsRow
		if err := rows.Scan(
			&i.Asset.ID,
			&i.Asset.Name,
			&i.Asset.WarrantyExpiry,
			&i.Asset.Status,
			&i.Asset.EndOfLife,
			&i.AssetFile.ContentHash,
			&i.AssetFile.MimeType,
			&i.AssetFile.OriginalFilename,
			&i.AssetFile.Category,
			&i.AssetFile.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsAfterCursor = `-- name: ListAssetsAfterCursor :many
SELECT asset.id, asset.name, asset.warranty_expiry, asset.status, asset.end_of_life, asset_file.content_hash, asset_file.mime_type, asset_file.original_filename, asset_file.category, asset_file.asset_id
FROM asset
INNER JOIN asset_file
  ON asset.id = asset_file.asset_id
WHERE asset.id > ?
ORDER BY asset.id
LIMIT ?
`

type ListAssetsAfterCursorRow struct {
	Asset     Asset     `json:"asset"`
	AssetFile AssetFile `json:"asset_file"`
}

func (q *Queries) ListAssetsAfterCursor(ctx context.Context, iD uuid.UUID, limit int64) ([]*ListAssetsAfterCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsAfterCursor, iD, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAssetsAfterCursorRow
	for rows.Next() {
		var i ListAssetsAfterCursorRow
		if err := rows.Scan(
			&i.Asset.ID,
			&i.Asset.Name,
			&i.Asset.WarrantyExpiry,
			&i.Asset.Status,
			&i.Asset.EndOfLife,
			&i.AssetFile.ContentHash,
			&i.AssetFile.MimeType,
			&i.AssetFile.OriginalFilename,
			&i.AssetFile.Category,
			&i.AssetFile.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsAfterFirst = `-- name: ListAssetsAfterFirst :many
SELECT asset.id, asset.name, asset.warranty_expiry, asset.status, asset.end_of_life, asset_file.content_hash, asset_file.mime_type, asset_file.original_filename, asset_file.category, asset_file.asset_id
FROM asset
INNER JOIN asset_file
  ON asset.id = asset_file.asset_id
ORDER BY asset.id
LIMIT ?
`

type ListAssetsAfterFirstRow struct {
	Asset     Asset     `json:"asset"`
	AssetFile AssetFile `json:"asset_file"`
}

func (q *Queries) ListAssetsAfterFirst(ctx context.Context, limit int64) ([]*ListAssetsAfterFirstRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsAfterFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAssetsAfterFirstRow
	for rows.Next() {
		var i ListAssetsAfterFirstRow
		if err := rows.Scan(
			&i.Asset.ID,
			&i.Asset.Name,
			&i.Asset.WarrantyExpiry,
			&i.Asset.Status,
			&i.Asset.EndOfLife,
			&i.AssetFile.ContentHash,
			&i.AssetFile.MimeType,
			&i.AssetFile.OriginalFilename,
			&i.AssetFile.Category,
			&i.AssetFile.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAsset = `-- name: ReadAsset :one
SELECT asset.id, asset.name, asset.warranty_expiry, asset.status, asset.end_of_life, asset_file.content_hash, asset_file.mime_type, asset_file.original_filename, asset_file.category, asset_file.asset_id
FROM asset
INNER JOIN asset_file
  ON asset.id = asset_file.asset_id
WHERE asset.id = ?
`

type ReadAssetRow struct {
	Asset     Asset     `json:"asset"`
	AssetFile AssetFile `json:"asset_file"`
}

func (q *Queries) ReadAsset(ctx context.Context, id uuid.UUID) (*ReadAssetRow, error) {
	row := q.db.QueryRowContext(ctx, readAsset, id)
	var i ReadAssetRow
	err := row.Scan(
		&i.Asset.ID,
		&i.Asset.Name,
		&i.Asset.WarrantyExpiry,
		&i.Asset.Status,
		&i.Asset.EndOfLife,
		&i.AssetFile.ContentHash,
		&i.AssetFile.MimeType,
		&i.AssetFile.OriginalFilename,
		&i.AssetFile.Category,
		&i.AssetFile.AssetID,
	)
	return &i, err
}
