// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_task.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listAllCompletionLogs = `-- name: ListAllCompletionLogs :many
SELECT id, completed_at, task_id FROM completion_logs
`

func (q *Queries) ListAllCompletionLogs(ctx context.Context) ([]*CompletionLog, error) {
	rows, err := q.db.QueryContext(ctx, listAllCompletionLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CompletionLog
	for rows.Next() {
		var i CompletionLog
		if err := rows.Scan(&i.ID, &i.CompletedAt, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTaskIDs = `-- name: ListAllTaskIDs :many
SELECT id FROM tasks
`

func (q *Queries) ListAllTaskIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listAllTaskIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT tasks.id, tasks.name, tasks.last_completed, tasks.next_date, tasks.start_date, tasks.end_date, tasks.asset_id, task_recurrences.id, task_recurrences.amount, task_recurrences.duration_type, task_recurrences.task_id
FROM tasks
INNER JOIN task_recurrences
  ON tasks.id = task_recurrences.task_id
ORDER BY tasks.id
`

type ListAllTasksRow struct {
	Task           Task           `json:"task"`
	TaskRecurrence TaskRecurrence `json:"task_recurrence"`
}

func (q *Queries) ListAllTasks(ctx context.Context) ([]*ListAllTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllTasksRow
	for rows.Next() {
		var i ListAllTasksRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.Name,
			&i.Task.LastCompleted,
			&i.Task.NextDate,
			&i.Task.StartDate,
			&i.Task.EndDate,
			&i.Task.AssetID,
			&i.TaskRecurrence.ID,
			&i.TaskRecurrence.Amount,
			&i.TaskRecurrence.DurationType,
			&i.TaskRecurrence.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionLogsAfterCursor = `-- name: ListCompletionLogsAfterCursor :many
SELECT id, completed_at, task_id FROM completion_logs
WHERE id > ?
ORDER BY id
LIMIT ?
`

func (q *Queries) ListCompletionLogsAfterCursor(ctx context.Context, iD uuid.UUID, limit int64) ([]*CompletionLog, error) {
	rows, err := q.db.QueryContext(ctx, listCompletionLogsAfterCursor, iD, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CompletionLog
	for rows.Next() {
		var i CompletionLog
		if err := rows.Scan(&i.ID, &i.CompletedAt, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionLogsAfterFirst = `-- name: ListCompletionLogsAfterFirst :many
SELECT id, completed_at, task_id FROM completion_logs
ORDER BY id
LIMIT ?
`

func (q *Queries) ListCompletionLogsAfterFirst(ctx context.Context, limit int64) ([]*CompletionLog, error) {
	rows, err := q.db.QueryContext(ctx, listCompletionLogsAfterFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CompletionLog
	for rows.Next() {
		var i CompletionLog
		if err := rows.Scan(&i.ID, &i.CompletedAt, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksAfterCursor = `-- name: ListTasksAfterCursor :many
SELECT tasks.id, tasks.name, tasks.last_completed, tasks.next_date, tasks.start_date, tasks.end_date, tasks.asset_id, task_recurrences.id, task_recurrences.amount, task_recurrences.duration_type, task_recurrences.task_id
FROM tasks
INNER JOIN task_recurrences
  ON tasks.id = task_recurrences.task_id
WHERE tasks.id > ?
ORDER BY tasks.id
LIMIT ?
`

type ListTasksAfterCursorRow struct {
	Task           Task           `json:"task"`
	TaskRecurrence TaskRecurrence `json:"task_recurrence"`
}

func (q *Queries) ListTasksAfterCursor(ctx context.Context, iD uuid.UUID, limit int64) ([]*ListTasksAfterCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksAfterCursor, iD, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTasksAfterCursorRow
	for rows.Next() {
		var i ListTasksAfterCursorRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.Name,
			&i.Task.LastCompleted,
			&i.Task.NextDate,
			&i.Task.StartDate,
			&i.Task.EndDate,
			&i.Task.AssetID,
			&i.TaskRecurrence.ID,
			&i.TaskRecurrence.Amount,
			&i.TaskRecurrence.DurationType,
			&i.TaskRecurrence.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksAfterFirst = `-- name: ListTasksAfterFirst :many
SELECT tasks.id, tasks.name, tasks.last_completed, tasks.next_date, tasks.start_date, tasks.end_date, tasks.asset_id, task_recurrences.id, task_recurrences.amount, task_recurrences.duration_type, task_recurrences.task_id
FROM tasks
INNER JOIN task_recurrences
  ON tasks.id = task_recurrences.task_id
ORDER BY tasks.id
LIMIT ?
`

type ListTasksAfterFirstRow struct {
	Task           Task           `json:"task"`
	TaskRecurrence TaskRecurrence `json:"task_recurrence"`
}

func (q *Queries) ListTasksAfterFirst(ctx context.Context, limit int64) ([]*ListTasksAfterFirstRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksAfterFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTasksAfterFirstRow
	for rows.Next() {
		var i ListTasksAfterFirstRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.Name,
			&i.Task.LastCompleted,
			&i.Task.NextDate,
			&i.Task.StartDate,
			&i.Task.EndDate,
			&i.Task.AssetID,
			&i.TaskRecurrence.ID,
			&i.TaskRecurrence.Amount,
			&i.TaskRecurrence.DurationType,
			&i.TaskRecurrence.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCompletionLog = `-- name: ReadCompletionLog :one
SELECT id, completed_at, task_id FROM completion_logs
WHERE id = ?
`

func (q *Queries) ReadCompletionLog(ctx context.Context, id uuid.UUID) (*CompletionLog, error) {
	row := q.db.QueryRowContext(ctx, readCompletionLog, id)
	var i CompletionLog
	err := row.Scan(&i.ID, &i.CompletedAt, &i.TaskID)
	return &i, err
}

const readTaskByID = `-- name: ReadTaskByID :one
SELECT sql.embed(tasks), task_recurrences.id, task_recurrences.amount, task_recurrences.duration_type, task_recurrences.task_id
FROM tasks
INNER JOIN task_recurrences
  ON tasks.id = task_recurrences.task_id
WHERE tasks.id = ?
`

type ReadTaskByIDRow struct {
	Embed          interface{}    `json:"embed"`
	TaskRecurrence TaskRecurrence `json:"task_recurrence"`
}

func (q *Queries) ReadTaskByID(ctx context.Context, id uuid.UUID) (*ReadTaskByIDRow, error) {
	row := q.db.QueryRowContext(ctx, readTaskByID, id)
	var i ReadTaskByIDRow
	err := row.Scan(
		&i.Embed,
		&i.TaskRecurrence.ID,
		&i.TaskRecurrence.Amount,
		&i.TaskRecurrence.DurationType,
		&i.TaskRecurrence.TaskID,
	)
	return &i, err
}
