// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_asset.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAssetFileRefsByID = `-- name: CountAssetFileRefsByID :one
SELECT COUNT(*)
FROM asset_files
WHERE content_hash = ?
`

func (q *Queries) CountAssetFileRefsByID(ctx context.Context, contentHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetFileRefsByID, contentHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllAssetIDs = `-- name: ListAllAssetIDs :many
SELECT id FROM assets
`

func (q *Queries) ListAllAssetIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAssets = `-- name: ListAllAssets :many
SELECT id, name
FROM assets
ORDER BY assets.id
`

type ListAllAssetsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListAllAssets(ctx context.Context) ([]*ListAllAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllAssetsRow
	for rows.Next() {
		var i ListAllAssetsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsAfterCursor = `-- name: ListAssetsAfterCursor :many
SELECT id, name
FROM assets
WHERE assets.id > ?
ORDER BY assets.id
LIMIT ?
`

type ListAssetsAfterCursorRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListAssetsAfterCursor(ctx context.Context, iD uuid.UUID, limit int64) ([]*ListAssetsAfterCursorRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsAfterCursor, iD, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAssetsAfterCursorRow
	for rows.Next() {
		var i ListAssetsAfterCursorRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsAfterFirst = `-- name: ListAssetsAfterFirst :many
SELECT id, name
FROM assets
ORDER BY assets.id
LIMIT ?
`

type ListAssetsAfterFirstRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListAssetsAfterFirst(ctx context.Context, limit int64) ([]*ListAssetsAfterFirstRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsAfterFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAssetsAfterFirstRow
	for rows.Next() {
		var i ListAssetsAfterFirstRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readAsset = `-- name: ReadAsset :one
SELECT assets.id, assets.name, assets.warranty_expiry, assets.availability, assets.attention_needed, assets.end_of_life, asset_files.asset_id, asset_files.content_hash, asset_files.original_filename
FROM assets
INNER JOIN asset_files
  ON assets.id = asset_files.asset_id
WHERE assets.id = ?
`

type ReadAssetRow struct {
	Asset     Asset     `json:"asset"`
	AssetFile AssetFile `json:"asset_file"`
}

func (q *Queries) ReadAsset(ctx context.Context, id uuid.UUID) (*ReadAssetRow, error) {
	row := q.db.QueryRowContext(ctx, readAsset, id)
	var i ReadAssetRow
	err := row.Scan(
		&i.Asset.ID,
		&i.Asset.Name,
		&i.Asset.WarrantyExpiry,
		&i.Asset.Availability,
		&i.Asset.AttentionNeeded,
		&i.Asset.EndOfLife,
		&i.AssetFile.AssetID,
		&i.AssetFile.ContentHash,
		&i.AssetFile.OriginalFilename,
	)
	return &i, err
}

const readAttentionNeededByID = `-- name: ReadAttentionNeededByID :one
SELECT attention_needed
FROM assets
WHERE id = ?
`

func (q *Queries) ReadAttentionNeededByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, readAttentionNeededByID, id)
	var attention_needed string
	err := row.Scan(&attention_needed)
	return attention_needed, err
}

const readAvailabilityByID = `-- name: ReadAvailabilityByID :one
SELECT availability
FROM assets
WHERE id = ?
`

func (q *Queries) ReadAvailabilityByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, readAvailabilityByID, id)
	var availability string
	err := row.Scan(&availability)
	return availability, err
}

const readContentHashByAssetID = `-- name: ReadContentHashByAssetID :many
SELECT content_hash
FROM asset_files
WHERE asset_id = ?
`

func (q *Queries) ReadContentHashByAssetID(ctx context.Context, assetID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, readContentHashByAssetID, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var content_hash string
		if err := rows.Scan(&content_hash); err != nil {
			return nil, err
		}
		items = append(items, content_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readPathFromContentHash = `-- name: ReadPathFromContentHash :one
SELECT path
FROM files
WHERE content_hash = ?
`

func (q *Queries) ReadPathFromContentHash(ctx context.Context, contentHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, readPathFromContentHash, contentHash)
	var path string
	err := row.Scan(&path)
	return path, err
}
