// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_asset.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateAssetByID = `-- name: UpdateAssetByID :execrows
UPDATE asset
SET
  name = ?,
  warranty_expiry = ?,
  status = ?,
  end_of_life = ?
WHERE id = ?
`

type UpdateAssetByIDParams struct {
	Name           string         `json:"name"`
	WarrantyExpiry sql.NullTime   `json:"warranty_expiry"`
	Status         sql.NullString `json:"status"`
	EndOfLife      sql.NullTime   `json:"end_of_life"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAssetByID(ctx context.Context, arg UpdateAssetByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetByID,
		arg.Name,
		arg.WarrantyExpiry,
		arg.Status,
		arg.EndOfLife,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetEOLByID = `-- name: UpdateAssetEOLByID :execrows
UPDATE asset
SET end_of_life = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetEOLByID(ctx context.Context, endOfLife sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetEOLByID, endOfLife, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetFileByID = `-- name: UpdateAssetFileByID :execrows
UPDATE asset_file SET
  content_hash = ?,
  mime_type = ?,
  original_filename = ?,
  category = ?
WHERE asset_id = ?
`

type UpdateAssetFileByIDParams struct {
	ContentHash      string `json:"content_hash"`
	MimeType         string `json:"mime_type"`
	OriginalFilename string `json:"original_filename"`
	Category         string `json:"category"`
	AssetID          string `json:"asset_id"`
}

func (q *Queries) UpdateAssetFileByID(ctx context.Context, arg UpdateAssetFileByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetFileByID,
		arg.ContentHash,
		arg.MimeType,
		arg.OriginalFilename,
		arg.Category,
		arg.AssetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetNameByID = `-- name: UpdateAssetNameByID :execrows
UPDATE asset
SET name = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetNameByID(ctx context.Context, name string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetNameByID, name, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetStatusByID = `-- name: UpdateAssetStatusByID :execrows
UPDATE asset
SET status = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetStatusByID(ctx context.Context, status sql.NullString, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetStatusByID, status, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetWarrantyByID = `-- name: UpdateAssetWarrantyByID :execrows
UPDATE asset
SET warranty_expiry = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetWarrantyByID(ctx context.Context, warrantyExpiry sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetWarrantyByID, warrantyExpiry, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
