// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_asset.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateAssetAvailabilityByID = `-- name: UpdateAssetAvailabilityByID :execrows
UPDATE assets
SET availability = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetAvailabilityByID(ctx context.Context, availability string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetAvailabilityByID, availability, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetByID = `-- name: UpdateAssetByID :execrows
UPDATE assets
SET
  name = ?,
  warranty_expiry = ?,
  availability = ?,
  attention_needed = ?,
  end_of_life = ?
WHERE id = ?
`

type UpdateAssetByIDParams struct {
	Name            string       `json:"name"`
	WarrantyExpiry  sql.NullTime `json:"warranty_expiry"`
	Availability    string       `json:"availability"`
	AttentionNeeded string       `json:"attention_needed"`
	EndOfLife       sql.NullTime `json:"end_of_life"`
	ID              uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateAssetByID(ctx context.Context, arg UpdateAssetByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetByID,
		arg.Name,
		arg.WarrantyExpiry,
		arg.Availability,
		arg.AttentionNeeded,
		arg.EndOfLife,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetEOLByID = `-- name: UpdateAssetEOLByID :execrows
UPDATE assets
SET end_of_life = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetEOLByID(ctx context.Context, endOfLife sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetEOLByID, endOfLife, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetNameByID = `-- name: UpdateAssetNameByID :execrows
UPDATE assets
SET name = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetNameByID(ctx context.Context, name string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetNameByID, name, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetNeedsAttentionByID = `-- name: UpdateAssetNeedsAttentionByID :execrows
UPDATE assets
SET attention_needed = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetNeedsAttentionByID(ctx context.Context, attentionNeeded string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetNeedsAttentionByID, attentionNeeded, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetWarrantyByID = `-- name: UpdateAssetWarrantyByID :execrows
UPDATE assets
SET warranty_expiry = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetWarrantyByID(ctx context.Context, warrantyExpiry sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetWarrantyByID, warrantyExpiry, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
