// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_task.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateAmountByID = `-- name: UpdateAmountByID :execrows
UPDATE task_recurrences
SET amount = ?
WHERE id = ?
`

func (q *Queries) UpdateAmountByID(ctx context.Context, amount int64, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAmountByID, amount, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetID = `-- name: UpdateAssetID :execrows
UPDATE tasks
SET asset_id = ?
WHERE id = ?
`

func (q *Queries) UpdateAssetID(ctx context.Context, assetID string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetID, assetID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDurationTypeByID = `-- name: UpdateDurationTypeByID :execrows
UPDATE task_recurrences
SET duration_type = ?
WHERE id = ?
`

func (q *Queries) UpdateDurationTypeByID(ctx context.Context, durationType string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDurationTypeByID, durationType, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEndDateByID = `-- name: UpdateEndDateByID :execrows
UPDATE tasks
SET end_date = ?
WHERE id = ?
`

func (q *Queries) UpdateEndDateByID(ctx context.Context, endDate sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateEndDateByID, endDate, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLastCompletedByID = `-- name: UpdateLastCompletedByID :execrows
UPDATE tasks
SET last_completed = ?
WHERE id = ?
`

func (q *Queries) UpdateLastCompletedByID(ctx context.Context, lastCompleted sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLastCompletedByID, lastCompleted, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNextDateByID = `-- name: UpdateNextDateByID :execrows
UPDATE tasks
SET next_date = ?
WHERE id = ?
`

func (q *Queries) UpdateNextDateByID(ctx context.Context, nextDate sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNextDateByID, nextDate, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateStartDateByID = `-- name: UpdateStartDateByID :execrows
UPDATE tasks
SET start_date = ?
WHERE id = ?
`

func (q *Queries) UpdateStartDateByID(ctx context.Context, startDate sql.NullTime, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStartDateByID, startDate, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskByID = `-- name: UpdateTaskByID :execrows
UPDATE tasks
SET
  name = ?,
  last_completed = ?,
  next_date = ?,
  start_date = ?,
  end_date = ?,
  asset_id = ?
WHERE id = ?
`

type UpdateTaskByIDParams struct {
	Name          string       `json:"name"`
	LastCompleted sql.NullTime `json:"last_completed"`
	NextDate      sql.NullTime `json:"next_date"`
	StartDate     sql.NullTime `json:"start_date"`
	EndDate       sql.NullTime `json:"end_date"`
	AssetID       string       `json:"asset_id"`
	ID            uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateTaskByID(ctx context.Context, arg UpdateTaskByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskByID,
		arg.Name,
		arg.LastCompleted,
		arg.NextDate,
		arg.StartDate,
		arg.EndDate,
		arg.AssetID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskNameByID = `-- name: UpdateTaskNameByID :execrows
UPDATE tasks
SET name = ?
WHERE id = ?
`

func (q *Queries) UpdateTaskNameByID(ctx context.Context, name string, iD uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskNameByID, name, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTaskRecurrenceByID = `-- name: UpdateTaskRecurrenceByID :execrows
UPDATE task_recurrences
SET
  amount = ?,
  duration_type = ?
WHERE id = ?
`

type UpdateTaskRecurrenceByIDParams struct {
	Amount       int64     `json:"amount"`
	DurationType string    `json:"duration_type"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTaskRecurrenceByID(ctx context.Context, arg UpdateTaskRecurrenceByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskRecurrenceByID, arg.Amount, arg.DurationType, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
